#ifndef COMPARISON_H
#define COMPARISON_H

#include <glib.h>

/**
 * @brief Compares a generated output file against an expected output file.
 *
 * @param generated_path Path to the file generated by the program.
 * @param expected_path Path to the file containing the expected output.
 * @param diff_line Pointer to an integer where the line number of the first difference will be stored (if any).
 * @return TRUE if files are identical, FALSE otherwise.
 */
gboolean compare_files(const char *generated_path, const char *expected_path, int *diff_line);

#endif